### ISSUE TITLE
TypeError: getHrefs expected a `string` but got: `object`

### ISSUE THREAD

**Issue by sinchanroy** [monotosh-k/gcp-docs#2]
gcp-docs
? Enter name of GCP product pubsub
? Enter name of sub-product(optional) 
? Enter path to save pdf file ./pdf/
? Select language for sample code Python

(node:6015) UnhandledPromiseRejectionWarning: TypeError: getHrefs expected a `string` but got: `object`
    at getHrefs (/Users/si.roy/gcp-docs/node_modules/get-hrefs/src/index.js:43:9)
    at saveNavLinks (/Users/si.roy/gcp-docs/src/main.js:39:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async downloadDocs (/Users/si.roy/gcp-docs/src/main.js:170:5)
    at async Proxy.cli (/Users/si.roy/gcp-docs/src/cli.js:97:5)
(node:6015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nowakj** [comment]
The structure of the Google Cloud documentation changed and the selectors used in the code don't work anymore.
I was able to get it to work eventually but had to do several fixes.
This project is not maintained :(

**Comment by dhaijma** [comment]
@nowakj could you please commit your fixes? Many thanks!
